### ISSUE TITLE
Upgrade Jackson to 2.16

### ISSUE THREAD

**Issue by philipp94831** [jcustenborder/kafka-config-provider-aws#20]
Kafka Connect 3.7 uses Jackson 2.16 which removes deprecated PascalCase property naming strategy:
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/PropertyNamingStrategy$PascalCaseStrategy
    at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<clinit>(AWSSecretsManagerClient.java:148)
    at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
    at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
    at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
    at com.github.jcustenborder.kafka.config.aws.SecretsManagerFactoryImpl.create(SecretsManagerFactoryImpl.java:34)
    at com.github.jcustenborder.kafka.config.aws.SecretsManagerConfigProvider.configure(SecretsManagerConfigProvider.java:137)
    at org.apache.kafka.common.config.AbstractConfig.instantiateConfigProviders(AbstractConfig.java:621)
    at org.apache.kafka.common.config.AbstractConfig.resolveConfigVariables(AbstractConfig.java:541)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
    at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:441)
    at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<init>(DistributedConfig.java:576)
    at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<init>(DistributedConfig.java:570)
    at org.apache.kafka.connect.cli.ConnectDistributed.createConfig(ConnectDistributed.java:111)
    at org.apache.kafka.connect.cli.ConnectDistributed.createConfig(ConnectDistributed.java:57)
    at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:123)
    at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
    at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:116)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategy$PascalCaseStrategy
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
    at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:124)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
    ... 17 more
```

Can you please update the plugin to support newer Kafka Connect versions?

**Comment by Gitzoz** [comment]
@philipp94831 I found your comment because I have the same error. I think the plugin here is deprecated and can be exchanged with this one https://github.com/confluentinc/csid-secrets-providers/tree/main/aws

**Comment by philipp94831** [comment]
Thanks @Gitzoz , that works beautifully
